#!/bin/bash
#echo "don't overwrite"
cp "$*".cpp ./Backup/"$*".cpp.bak
#if [ "$2" = "" ]; then
#echo "fault check arguments"
#fi
#if [ "$1" = "def" ]; then
cp ~/PS/Tool/default.cpp "$*".cpp
vi "$*".cpp
#elif [ "$1" = "clk" ]; then
#cp ~/PS/Tool/clock.cpp "$2"_clk.cpp
#vi "$2"_clk.cpp
#fi
	
